internal.auth.secret=This-is-internal-auth-secret-should-be-same-in-all-downstream-service
razorpay.key=rzp_test_RzSqheqmPrM9ad
razorpay.secret=P2q4cHycas6b66uOiP3yTSYB
webhook.secret.key=keysecretwebhook321