spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/user
    username: root
    password: D1d2d@78
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  cloud:
    feign:
        hystrix:
            enabled: true


server:
  port: 8080

eureka:
  client:
    server-url:
      defaultZone: http://localhost:8761/eureka/


